name: Create Cypress report
on:
  push:
    branches:
      - 'master'
  # Add this part if you want to schedule test rerun
  # schedule:
  #   - cron: '0 8 1-31 * *'

jobs:
  
  cypress-e2e-chrome81:
    name: Run on Chrome 81
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install a project with a clean slate
        run: |
          npm ci
          npx cypress cache path
          npx cypress cache list
          npx cypress verify
      
      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true
      
      - name: Copy test execution videos
        run: |
          mkdir public
          cp -r cypress/videos public/videos
      
      - name: Merge test results into one
        run: npm run report:merge
      
      - name: Generate HTML report
        run: npm run report:generate
      
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'